### ISSUE TITLE
Incrementing the "downAmount" input of the LoanAmountDetails Component

### ISSUE THREAD

**Issue by kirkdrichardson** [coffeeAndCodeMSO/mort_comp#1]
Upon incrementing, the downPercent input seems to be multiplied by 100 twice, so that the a 20% down payment of 100,000 on a 500,000 house, becomes a "2020%" down payment of 101,000 on the same 500,000 house.

Currently working on a mobx commit, so I just wanted to mark the issue. If it still exists when I finish, I'll look into it

**Comment by kirkdrichardson** [comment]
This is a result of `printableSingleDecimalPercent(value)` in `src/lib/formatting_helpers.js`
Combined with the `updateLoanAmountInput = (event) => {` function in `LoanAmountDetails.js`, the decimal value is multiplied by 100 twice. I'll fix this & change the default state (to correct the starting value which relied on the x100 in the formatting helper) in my mobx commit since it covers this as well.

**Comment by kirkdrichardson** [comment]
The decimal value of `downPercent` (see LoanAmountDetails) is nested more deeply than I thought. Ran into issues calculating other formulas. I'm going to decouple this from the mobx commit.

**Comment by rschultheis** [comment]
out of date
