### ISSUE TITLE
LoanAmountDetails, modifying value

### ISSUE THREAD

**Issue by kirkdrichardson** [coffeeAndCodeMSO/mort_comp#2]
- changing the value of the loan amount resets the other fields in the component
- this is handled in the `  updateLoanAmountInput` function:
```
      case "loanAmount":
        this.setState({loanAmount: Math.round(newValue), downAmount: '', downPercent: '', houseCost: ''});
        break;
```
Although  I modify this function in the transferring of state to a mobx store, I have tried to keep the logic of all functions essentially the same. Once state is transferred, it'll be easier to go back to these.

**Comment by rschultheis** [comment]
out of date
